import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import Vue from 'vue'


import { faPhone, faLocationDot, faMagnifyingGlass, faPersonDotsFromLine, faQuoteLeft, faUserTie, faGears, faComments, faFlag, faBriefcase, fa1, fa2, fa3, fa4, fa5, fa6, faCloud, faLaptopCode, faChartArea, faShuttleSpace, faFolderOpen, faDesktop, faTv, faAngleRight, faHouse, faUsers, faPaste, faBookmark, faEnvelope, faCircleArrowRight } from '@fortawesome/free-solid-svg-icons'
import { faFacebookF, faTwitter, faDribbble, faGoogle, faAndroid, faApple } from '@fortawesome/free-brands-svg-icons'
import { faBuilding, faRotate, faHouseChimney, faTruckMoving, faSuitcase, faGlobe, faLink, faGear, faLightbulb, faClock, faArrowRight, faArrowUpRightDots, faPeopleGroup, faChartPie, faSquarePlus, faSquarePollVertical, faRectangleList } from '@fortawesome/free-solid-svg-icons'
import { faYoutube, faInstagram, faLinkedinIn, faTiktok } from '@fortawesome/free-brands-svg-icons'

import { faWifi } from '@fortawesome/free-solid-svg-icons'
import { faAngleDown } from '@fortawesome/free-solid-svg-icons'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons'
import { faUser } from '@fortawesome/free-solid-svg-icons'
import { faSliders } from '@fortawesome/free-solid-svg-icons'
import { faLeaf } from '@fortawesome/free-solid-svg-icons'
import { faArrowsSpin } from '@fortawesome/free-solid-svg-icons'
import { faLayerGroup } from '@fortawesome/free-solid-svg-icons'
import { faCaretRight } from '@fortawesome/free-solid-svg-icons'
import { faAnglesRight } from '@fortawesome/free-solid-svg-icons'
import { faPlay } from '@fortawesome/free-solid-svg-icons'
import { faCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faHandHoldingHand } from '@fortawesome/free-solid-svg-icons'
import { faCircleQuestion } from '@fortawesome/free-solid-svg-icons'
import { faBuildingLock } from '@fortawesome/free-solid-svg-icons'
import { faComputer } from '@fortawesome/free-solid-svg-icons'
import { faMagnifyingGlassChart } from '@fortawesome/free-solid-svg-icons'
import { faFileCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faAward } from '@fortawesome/free-solid-svg-icons'
import { faCubes } from '@fortawesome/free-solid-svg-icons'
import { faPhoneVolume } from '@fortawesome/free-solid-svg-icons'
import { faMessage } from '@fortawesome/free-regular-svg-icons'
import { faCirclePlus } from '@fortawesome/free-solid-svg-icons'
import { faCircleMinus } from '@fortawesome/free-solid-svg-icons'
import { faCodeBranch } from '@fortawesome/free-solid-svg-icons'
import { faFolderTree } from '@fortawesome/free-solid-svg-icons'
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons'
import { faTag } from '@fortawesome/free-solid-svg-icons'
import { faEye } from '@fortawesome/free-solid-svg-icons'
import { faPlus } from '@fortawesome/free-solid-svg-icons'
import { faMinus } from '@fortawesome/free-solid-svg-icons'
import { faRoad } from '@fortawesome/free-solid-svg-icons'
import { faVideo } from '@fortawesome/free-solid-svg-icons'
import { faDroplet } from '@fortawesome/free-solid-svg-icons'
import { faChartColumn } from '@fortawesome/free-solid-svg-icons'
import { faUpRightAndDownLeftFromCenter } from '@fortawesome/free-solid-svg-icons'

library.add( faDribbble, fa1, fa2, fa3, fa4, fa5, fa6, faCloud, faAndroid, faDesktop, faApple, faTv, faHouse, faPaste, faBookmark, faEnvelope, faCircleArrowRight, faRotate, faHouseChimney, faTruckMoving, faSuitcase, faUsers, faLightbulb, faGlobe, faArrowUpRightDots, faPeopleGroup, faChartPie, faSquarePlus, faSquarePollVertical, faRectangleList, faTiktok, faEnvelope, faPhone, faClock,faPlus, faMinus, faRoad, faVideo, faDroplet, faGoogle, faGear, faBuilding, faChartColumn, faLink, faFacebookF, faTwitter, faLinkedinIn, faWifi, faYoutube, faMagnifyingGlass, faAngleDown, faAngleLeft, faFlag, faSliders, faAngleRight, faLeaf, faUser, faArrowsSpin, faLayerGroup, faUserTie, faGears, faComments, faBriefcase, faCaretRight, faAnglesRight, faPlay, faCircleCheck, faHandHoldingHand, faCircleQuestion, faBuildingLock, faComputer, faMagnifyingGlassChart, faFileCircleCheck, faAward, faCubes, faFolderOpen, faShuttleSpace, faPersonDotsFromLine, faLaptopCode, faPhoneVolume, faLocationDot, faMessage, faCirclePlus, faCircleMinus, faInstagram, faCloud, faChartArea, faCodeBranch, faFolderTree, faArrowLeft, faArrowRight, faUpRightAndDownLeftFromCenter, faTag, faEye, faQuoteLeft)

Vue.component('font-awesome-icon', FontAwesomeIcon)